{% set version="2016.7" %}

package:
  name: pytz
  version: {{ version }}

source:
  fn: pytz-{{ version }}.tar.bz2
  url: https://pypi.io/packages/source/p/pytz/pytz-{{ version }}.tar.bz2
  sha256: 6eab31709e3a4aea748457707da45e805b650cbb352583805d2417de2a1dd71e

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - pytz

about:
  home: http://pythonhosted.org/pytz/
  license: MIT
  license_file: LICENSE.txt
  summary: World timezone definitions, modern and historical
  description: |
    pytz brings the Olson tz database into Python. This library allows
    accurate and cross platform timezone calculations using Python 2.4 or
    higher. It also solves the issue of ambiguous times at the end of daylight
    saving time.
  doc_url: http://pythonhosted.org/pytz/
  dev_url: https://github.com/newvem/pytz

extra:
  recipe-maintainers:
    - msarahan
    - ocefpaf
