travis:
  secure:
    BINSTAR_TOKEN: uEjxxxSH0rBrAsZmHSE/eh0swhDpCXGJwrlKGmIhAorVoqsPtWWYN0Nq4OX7bH7tvvKvx30vQjZmveip0Sbq+qkiHttSh7u6bSzjshEEJ8WoZk7Gk5hdrehQqcjiC46C5JL/4n55Gy/JQbahfuJgjkjfJvnhSbsuty9QS10v6O0WrM+oz30iGKVPrQVxUEuSulQ0QqbBMmy7RptbPjtukeCNlFxgfmDDBoRRib8+v9FUHR1V+WFWtehn2EwEEZSR65vK9JaaoYa6wxxmp2CdstSoABX6Vrn/Q9C3WLm79ItuwpVI2OZ+aB+x6XjmHoMEL2ArtiqE6ew1vdeMB+cmX0Ra5JMoZn3C8mfi+Km8qzQe9pQ+/dG6dt64E+XfbDIXN3uyMKVugfbX1m0hpuaK28nxBoR0Z/3HDHYIHSEgU5Qqzf24cLjoHZUfEcuaSK5iUCr+hHhleavVcf0YSL6s/CxlQPHEXHy+z7Nftz5zRyg+5VA8Y7AECMU0dXGxZ00p43taw7ZTVRh1wUcotJz/Rht5Y+LAOkFf4iRnCqJoiTO0YYSsdio7OS1MfYe68rmhVsgJXGA/FPRXchLYyct9RQ9t/CPuY+/Hfm5CqJQGx2vZC7n5JpFeKqDY/AyqFqnjRkRZl8Tcf+/XhxWYuc9ZOP+1vE1rbgjy597nZ8zP47I=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
